name: Daily Commit Workflow

on:
  schedule:
    - cron: '30 6 * * *'
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Git (23f3002094@ds.study.iitm.ac.in)
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "23f3002094@ds.study.iitm.ac.in"

    - name: Make a dummy change
      run: echo "Last run: $(date)" > last_run.txt

    - name: Commit and Push Changes
      run: |
        set -e
        git add last_run.txt
        git commit -m "Automated daily commit"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
