name: Daily Commit Workflow

on:
  schedule:
    # Run daily at 7:30 AM UTC
    - cron: '30 7 * * *'
  workflow_dispatch: # for manual testing

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make daily commit - 23f3002094@ds.study.iitm.ac.in
        run: |
          echo "Daily update: $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Automated daily update"
          git push
