name: Daily Commit Workflow

on:
  schedule:
    # Runs every day at 06:15 AM UTC (adjust as needed)
    - cron: '15 6 * * *'
  workflow_dispatch:  # allows manual run

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Git with your email 23f3002094@ds.study.iitm.ac.in
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "23f3002094@ds.study.iitm.ac.in"

    - name: Make a dummy change
      run: |
        echo "Last run: $(date)" > last_run.txt

    - name: Commit and push changes
      run: |
        git add last_run.txt
        git commit -m "Automated daily commit"
        git push
      env:
        # Use GitHub token for authentication
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
